class UnicornProtocol:
    PORT = 1
    EEG_CHANNELS_COUNT = 8
    HEADER_LENGTH = 2
    BYTES_PER_BATTERY_LEVEL_CHANNEL = 1
    BATTERY_LEVEL_LENGTH = BYTES_PER_BATTERY_LEVEL_CHANNEL
    BATTERY_LEVEL_OFFSET = HEADER_LENGTH
    BYTES_PER_EEG_CHANNEL = 3
    PAYLOAD_LENGTH = 45
    ACC_CHANNELS_COUNT = 3
    GYROSCOPE_CHANNELS_COUNT = 3
    BYTES_PER_ACC_CHANNEL = 2
    FS = 250.0

    EEG_OFFSET = BATTERY_LEVEL_OFFSET + BATTERY_LEVEL_LENGTH
    ACC_LENGTH = ACC_CHANNELS_COUNT * BYTES_PER_ACC_CHANNEL
    ACC_OFFSET = EEG_OFFSET + (EEG_CHANNELS_COUNT * BYTES_PER_EEG_CHANNEL)
    BYTES_PER_GYR_CHANNEL = 2
    GYR_LENGTH = GYROSCOPE_CHANNELS_COUNT * BYTES_PER_GYR_CHANNEL
    GYR_OFFSET = ACC_OFFSET + ACC_LENGTH

    START_MSG = b'\x61\x7C\x87'
    STOP_MSG = b"\x63\x5C\xC5"

    def calibrate_ephys(x):
        return x * (4500000.0 / 50331642.0)
    
    def calibrate_accel(x):
        return x * (1.0 / 4096.0)
    
    def calibrate_gyro(x):
        return x * (1.0 / 32.8)